// Generated by CoffeeScript 1.7.1
(function() {
  var Pomodoro, Task;

  Pomodoro = (function() {
    function Pomodoro() {
      console.log(':::::::::::::::::::::::::::::::::::::');
      console.log(':: Starting pomodoro app');
      console.log(':::::::::::::::::::::::::::::::::::::');
      this.fbase = new Firebase("https://brilliant-heat-2062.firebaseio.com/");
      this.tasks_index = this.fbase.child('tasks');
      this.enableEvents();
    }

    Pomodoro.prototype.startTask = function(task) {
      console.log(':: Task started');
      task.start_time = Date.now();
      return this.tasks_index.push({
        id: task.id,
        title: task.title,
        date: task.start_time
      });
    };

    Pomodoro.prototype.enableEvents = function() {
      return this.tasks_index.on('value', function(snapshot) {
        var key, li, obj, tasks, _i, _len, _ref, _results;
        tasks = snapshot.val();
        $('#tasks').html('');
        _ref = Object.keys(tasks);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          key = _ref[_i];
          li = $('<li>').addClass('list-group-item');
          obj = tasks[key];
          li.append(obj.title);
          _results.push($('#tasks').append(li));
        }
        return _results;
      }, function(errorObject) {
        return console.log("The read failed: " + errorObject.code);
      });
    };

    return Pomodoro;

  })();

  Task = (function() {
    var generateId;

    Task.prototype.id = null;

    Task.prototype.start_time = null;

    Task.prototype.end_time = null;

    function Task(title) {
      this.title = title;
      this.id = generateId();
    }

    generateId = function() {
      var chars, result, today;
      chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
      today = new Date();
      result = today.valueOf().toString(16);
      result += chars.substr(Math.floor(Math.random() * chars.length), 1);
      return result += chars.substr(Math.floor(Math.random() * chars.length), 1);
    };

    return Task;

  })();

  $(function() {
    var pomodoro;
    pomodoro = new Pomodoro;
    return $('#startstop').on('click', function(e) {
      var task;
      if ($('#task-title').val() !== '') {
        task = new Task($('#task-title').val());
        return pomodoro.startTask(task);
      } else {
        return alert('Please, add a title for this task');
      }
    });
  });

}).call(this);
